using System;
using System.Collections.Generic;
using UltimateGalaxyRandomizer.Logic;
using UltimateGalaxyRandomizer.Logic.Equipment;

namespace UltimateGalaxyRandomizer.Resources
{
    public class Equipments
    {
        public static Dictionary<uint, Equipment> Boots = new Dictionary<uint, Equipment>()
        {
            {0x33D01FA2, new Equipment("Raimon boots")},
            {0xAAD94E18, new Equipment("Black boots")},
            {0xDDDE7E8E, new Equipment("Prodigy boots")},
            {0x43BAEB2D, new Equipment("Milky Way boots")},
            {0x34BDDBBB, new Equipment("Almighty Faith boots")},
            {0xADB48A01, new Equipment("Royal boots")},
            {0xDAB3BA97, new Equipment("Pirates Cove boots")},
            {0x4A0CA706, new Equipment("Lunar Sea boots")},
            {0x5DCC1E75, new Equipment("Alpine boots")},
            {0x2ACB2EE3, new Equipment("Kirkwood boots")},
            {0xB3C27F59, new Equipment("Mirage boots")},
            {0x5AA1DA6C, new Equipment("Universal boots")},
            {0x2DA6EAFA, new Equipment("Mount Olympus boots")},
            {0xB4AFBB40, new Equipment("Dragon Link boots")},
            {0xC3A88BD6, new Equipment("Eternal boots")},
            {0x53179647, new Equipment("Ancient boots")},
            {0x2410A6D1, new Equipment("Zero boots")},
            {0x76E14DB6, new Equipment("Reserve boots")},
            {0x01E67D20, new Equipment("Golden Oldies boots")},
            {0x98EF2C9A, new Equipment("Ivy Selective boots")},
            {0xEFE81C0C, new Equipment("Kids boots")},
            {0x3054CBCC, new Equipment("Sherwind boots")},
            {0xA95D9A76, new Equipment("Omega boots")},
            {0x403E3F43, new Equipment("White Deer sandals")},
            {0x37390FD5, new Equipment("Omega Z boots")},
            {0xD9376EF9, new Equipment("Zanark boots")},
            {0x49887368, new Equipment("Cascade boots")},
            {0x5E48CA1B, new Equipment("Zan boots")},
            {0x294FFA8D, new Equipment("Gihl boots")},
            {0xB046AB37, new Equipment("Gahl boots")},
            {0xC7419BA1, new Equipment("Ragnah boots")},
            {0x59250E02, new Equipment("Werewolf boots")},
            {0x2E223E94, new Equipment("Vampire boots")},
            {0xB72B6F2E, new Equipment("Nocturnal boots")},
            {0xC02C5FB8, new Equipment("Champion boots")},
            {0x50934229, new Equipment("Despairado boots")},
            {0x279472BF, new Equipment("Legendary boots")},
            {0x756599D8, new Equipment("Global boots")},
            {0x0262A94E, new Equipment("National boots")},
            {0x9B6BF8F4, new Equipment("Genesis boots")},
            {0xA89FF041, new Equipment("Fire boots")},
            {0xDF98C0D7, new Equipment("Waves boots")},
            {0x41FC5574, new Equipment("Shamshir boots")},
            {0x36FB65E2, new Equipment("Tiger boots")},
            {0xAFF23458, new Equipment("Wolf boots")},
            {0xD8F504CE, new Equipment("Resistance boots")},
            {0x484A195F, new Equipment("Silica boots")},
            {0x3F4D29C9, new Equipment("Naiadi boots")},
            {0x5F8AA02C, new Equipment("Magmavia boots")},
            {0x288D90BA, new Equipment("Fertilia boots")},
            {0xB184C100, new Equipment("Falam boots")},
            {0xC683F196, new Equipment("Ixar boots")},
            {0x58E76435, new Equipment("Knight boots")},
            {0x2FE054A3, new Equipment("Combat boots")},
            {0xB6E90519, new Equipment("Rankers boots")},
            {0xC1EE358F, new Equipment("Zeus boots")},
            {0x5151281E, new Equipment("Ogre boots")},
            {0x32127595, new Equipment("Thunder boots")},
            {0xAB1B242F, new Equipment("Discipline boots")},
            {0xDC1C14B9, new Equipment("Flurry boots")},
            {0x4278811A, new Equipment("Verdant boots")},
            {0x357FB18C, new Equipment("Combustion boots")},
            {0xAC76E036, new Equipment("Terra boots")},
            {0xDB71D0A0, new Equipment("Terror boots")},
            {0x4BCECD31, new Equipment("Sports shoes")},
            {0x3CC9FDA7, new Equipment("Smart boots")},
            {0x5C0E7442, new Equipment("Stripe boots")},
            {0x2B0944D4, new Equipment("Victory boots")},
            {0xB200156E, new Equipment("Power boots")},
            {0xC50725F8, new Equipment("Harlequin boots")},
            {0x5B63B05B, new Equipment("Boat boots")},
            {0x2C6480CD, new Equipment("Gentleman's boots")},
            {0xB56DD177, new Equipment("Devotion boots")},
            {0xC26AE1E1, new Equipment("Panther boots")},
            {0x52D5FC70, new Equipment("Echo boots")},
            {0x25D2CCE6, new Equipment("Uplifting boots")},
            {0x77232781, new Equipment("Vitality boots")},
            {0x00241717, new Equipment("Premium boots")},
            {0x4D233F89, new Equipment("Waterproof boots")},
            {0xD42A6E33, new Equipment("Tonghanian boots")},
            {0xA32D5EA5, new Equipment("Dashing sandals")},
            {0x3D49CB06, new Equipment("Bright sandals")},
            {0x4A4EFB90, new Equipment("Warrior sandals")},
            {0xD347AA2A, new Equipment("Shinsengumi sandals")},
            {0xA4409ABC, new Equipment("Noble boots")},
            {0x34FF872D, new Equipment("Peasant boots")},
            {0x43F8B7BB, new Equipment("Aristocrat boots")},
            {0x11095CDC, new Equipment("Sabaton boots")},
            {0x660E6C4A, new Equipment("Eastern boots")},
            {0xFF073DF0, new Equipment("Fortress boots")},
            {0x88000D66, new Equipment("Automated boots")},
            {0x166498C5, new Equipment("Binary boots")},
            {0x3C8BA131, new Equipment("Sandstorm boots")},
            {0x4B8C91A7, new Equipment("Erg boots")},
            {0xD285C01D, new Equipment("Current boots")},
            {0xA582F08B, new Equipment("Float boots")},
            {0x353DED1A, new Equipment("Volcano boots")},
            {0x423ADD8C, new Equipment("Ash boots")},
            {0x10CB36EB, new Equipment("Sunlight boots")},
            {0x67CC067D, new Equipment("Hunting boots")},
        };

        public static Dictionary<uint, Equipment> Gloves = new Dictionary<uint, Equipment>()
        {
            {0xAB975F2F, new Equipment("Raimon gloves")},
            {0x329E0E95, new Equipment("Black gloves")},
            {0x45993E03, new Equipment("Prodigy gloves")},
            {0xDBFDABA0, new Equipment("Milky Way gloves")},
            {0xACFA9B36, new Equipment("Almighty Faith gloves")},
            {0x35F3CA8C, new Equipment("Royal gloves")},
            {0x42F4FA1A, new Equipment("Pirates Cove gloves")},
            {0xD24BE78B, new Equipment("Lunar Sea gloves")},
            {0xC58B5EF8, new Equipment("Alpine gloves")},
            {0xB28C6E6E, new Equipment("Kirkwood gloves")},
            {0x2B853FD4, new Equipment("Mirage gloves")},
            {0xC2E69AE1, new Equipment("Universal gloves")},
            {0xB5E1AA77, new Equipment("Mount Olympus gloves")},
            {0x2CE8FBCD, new Equipment("Dragon Link gloves")},
            {0x5BEFCB5B, new Equipment("Eternal gloves")},
            {0xCB50D6CA, new Equipment("Ancient gloves")},
            {0xBC57E65C, new Equipment("Zero gloves")},
            {0xEEA60D3B, new Equipment("Reserve gloves")},
            {0x99A13DAD, new Equipment("Golden Oldies gloves")},
            {0x00A86C17, new Equipment("Ivy Selective gloves")},
            {0x77AF5C81, new Equipment("Kids gloves")},
            {0xA8138B41, new Equipment("Sherwind gloves")},
            {0x311ADAFB, new Equipment("Omega gloves")},
            {0xD8797FCE, new Equipment("White Deer gloves")},
            {0xAF7E4F58, new Equipment("Omega Z gloves")},
            {0x41702E74, new Equipment("Zanark gloves")},
            {0xD1CF33E5, new Equipment("Cascade gloves")},
            {0xC60F8A96, new Equipment("Zan gloves")},
            {0xB108BA00, new Equipment("Gihl gloves")},
            {0x2801EBBA, new Equipment("Gahl gloves")},
            {0x5F06DB2C, new Equipment("Ragnah gloves")},
            {0xC1624E8F, new Equipment("Werewolf gloves")},
            {0xB6657E19, new Equipment("Vampire gloves")},
            {0x2F6C2FA3, new Equipment("Nocturnal gloves")},
            {0x586B1F35, new Equipment("Champion gloves")},
            {0xC8D402A4, new Equipment("Despairado gloves")},
            {0xBFD33232, new Equipment("Legendary gloves")},
            {0xED22D955, new Equipment("Global gloves")},
            {0x9A25E9C3, new Equipment("National gloves")},
            {0x032CB879, new Equipment("Genesis gloves")},
            {0x30D8B0CC, new Equipment("Fire Gloves")},
            {0x47DF805A, new Equipment("Waves gloves")},
            {0xD9BB15F9, new Equipment("Shamshir gloves")},
            {0xAEBC256F, new Equipment("Tiger gloves")},
            {0x37B574D5, new Equipment("Wolf gloves")},
            {0x40B24443, new Equipment("Resistance gloves")},
            {0xD00D59D2, new Equipment("Silica gloves")},
            {0xA70A6944, new Equipment("Naiadi gloves")},
            {0xC7CDE0A1, new Equipment("Magmavia gloves")},
            {0xB0CAD037, new Equipment("Fertilia gloves")},
            {0x29C3818D, new Equipment("Falam gloves")},
            {0x5EC4B11B, new Equipment("Ixar gloves")},
            {0xC0A024B8, new Equipment("Knight gloves")},
            {0xB7A7142E, new Equipment("Combat gloves")},
            {0x2EAE4594, new Equipment("Rankers gloves")},
            {0x59A97502, new Equipment("Zeus gloves")},
            {0xC9166893, new Equipment("Ogre gloves")},
            {0xAA553518, new Equipment("Thunder gloves")},
            {0x335C64A2, new Equipment("Discipline gloves")},
            {0x445B5434, new Equipment("Flurry gloves")},
            {0xDA3FC197, new Equipment("Verdant gloves")},
            {0xAD38F101, new Equipment("Combustion gloves")},
            {0x3431A0BB, new Equipment("Terra gloves")},
            {0x4336902D, new Equipment("Terror gloves")},
            {0xD3898DBC, new Equipment("Sports gloves")},
            {0xA48EBD2A, new Equipment("Smart gloves")},
            {0xC44934CF, new Equipment("Stripe gloves")},
            {0xB34E0459, new Equipment("Victory gloves")},
            {0x2A4755E3, new Equipment("Power gloves")},
            {0x5D406575, new Equipment("Harlequin gloves")},
            {0xC324F0D6, new Equipment("Sailor gloves")},
            {0xB423C040, new Equipment("Gentleman's gloves")},
            {0x2D2A91FA, new Equipment("Devotion gloves")},
            {0x5A2DA16C, new Equipment("Panther gloves")},
            {0xCA92BCFD, new Equipment("Echo gloves")},
            {0xBD958C6B, new Equipment("Uplifting gloves")},
            {0xEF64670C, new Equipment("Vitality gloves")},
            {0x9863579A, new Equipment("Premium gloves")},
            {0xD5647F04, new Equipment("Waterproof gloves")},
            {0x4C6D2EBE, new Equipment("Tonghanian gloves")},
            {0x3B6A1E28, new Equipment("Dashing gloves")},
            {0xA50E8B8B, new Equipment("Bright gloves")},
            {0xD209BB1D, new Equipment("Warrior gloves")},
            {0x4B00EAA7, new Equipment("Shinsengumi gloves")},
            {0x3C07DA31, new Equipment("Noble gloves")},
            {0xACB8C7A0, new Equipment("Peasant gloves")},
            {0xDBBFF736, new Equipment("Aristocrat gloves")},
            {0x894E1C51, new Equipment("Gauntlets")},
            {0xFE492CC7, new Equipment("Eastern gloves")},
            {0x67407D7D, new Equipment("Fortress gloves")},
            {0x10474DEB, new Equipment("Automated gloves")},
            {0x8E23D848, new Equipment("Binary gloves")},
            {0xA4CCE1BC, new Equipment("Sandstorm gloves")},
            {0xD3CBD12A, new Equipment("Erg gloves")},
            {0x4AC28090, new Equipment("Current gloves")},
            {0x3DC5B006, new Equipment("Float gloves")},
            {0xAD7AAD97, new Equipment("Volcano gloves")},
            {0xDA7D9D01, new Equipment("Ash gloves")},
            {0x888C7666, new Equipment("Sunlight gloves")},
            {0xFF8B46F0, new Equipment("Hunting gloves")},
        };

        public static Dictionary<uint, Equipment> Bracelets = new Dictionary<uint, Equipment>()
        {
            {0x0A0C7C49, new Equipment("Red bracelet")},
            {0x93052DF3, new Equipment("Leather bracelet")},
            {0xE4021D65, new Equipment("Colourful bracelet")},
            {0x7A6688C6, new Equipment("Passion bracelet")},
            {0x0D61B850, new Equipment("Rosary ball bracelet")},
            {0x9468E9EA, new Equipment("Friendship bracelet")},
            {0xE36FD97C, new Equipment("Muscle bracelet")},
            {0x73D0C4ED, new Equipment("Fireball bracelet")},
            {0x04D7F47B, new Equipment("Youthful bracelet")},
            {0x64107D9E, new Equipment("Fashionable bracelet")},
            {0x13174D08, new Equipment("Victory bracelet")},
            {0x8A1E1CB2, new Equipment("Wild bracelet")},
            {0xFD192C24, new Equipment("Lucky bracelet")},
            {0x637DB987, new Equipment("Wish bracelet")},
            {0x147A8911, new Equipment("Active bracelet")},
            {0x8D73D8AB, new Equipment("Rainbow bracelet")},
            {0xFA74E83D, new Equipment("Foreign bracelet")},
            {0x6ACBF5AC, new Equipment("Cosmos bracelet")},
            {0x1DCCC53A, new Equipment("Courage bracelet")},
            {0x4F3D2E5D, new Equipment("Sacred bracelet")},
            {0x383A1ECB, new Equipment("Paradise bracelet")},
            {0xA1334F71, new Equipment("Tezcat's bracelet")},
            {0xD6347FE7, new Equipment("Dirty bracelet")},
            {0x4850EA44, new Equipment("Angelic bracelet")},
            {0x3F57DAD2, new Equipment("Demonic bracelet")},
        };

        public static Dictionary<uint, Equipment> Pendants = new Dictionary<uint, Equipment>()
        {
            {0xB5446D0C, new Equipment("Drop pendant")},
            {0x2C4D3CB6, new Equipment("Diamond pendant")},
            {0x5B4A0C20, new Equipment("Heart pendant")},
            {0xC52E9983, new Equipment("Cross pendant")},
            {0xB229A915, new Equipment("Amulet pendant")},
            {0x2B20F8AF, new Equipment("Fashionable pendant")},
            {0x5C27C839, new Equipment("Silver pendant")},
            {0xCC98D5A8, new Equipment("Chain pendant")},
            {0xBB9FE53E, new Equipment("Gothic pendan")},
            {0xDB586CDB, new Equipment("Inazuma pendant")},
            {0xAC5F5C4D, new Equipment("Fireball pendant")},
            {0x35560DF7, new Equipment("Youth pendant")},
            {0x42513D61, new Equipment("Vow pendant")},
            {0xDC35A8C2, new Equipment("Victory pendant")},
            {0xAB329854, new Equipment("Wish pendant")},
            {0x323BC9EE, new Equipment("Small pendant")},
            {0x453CF978, new Equipment("Bravery pendant")},
            {0xD583E4E9, new Equipment("Pure pendant")},
            {0xA284D47F, new Equipment("Paradise pendant")},
            {0xF0753F18, new Equipment("Infinity pendant")},
            {0x87720F8E, new Equipment("Rusty pendant")},
            {0x1E7B5E34, new Equipment("Guardian pendant")},
            {0x697C6EA2, new Equipment("Destruction pendant")},
            {0xF718FB01, new Equipment("Learning pendant")},
            {0x801FCB97, new Equipment("Treasure pendant")},
        };
    }
}
